---
pipelines:
- name: test-pipeline
  config_file: pipeline-templates/pipeline.yaml
  exposed: true
  team: main
  vars_files:
    - pipeline-templates/config.yaml
  vars:
    my_var: "foo"
    my_complex_var: {abc: 123}
